# Generated by Django 3.0.5 on 2020-04-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('userid', models.CharField(max_length=30)),
                ('busid', models.CharField(max_length=30)),
                ('bus_name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=30)),
                ('nos', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bus',
            name='nos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bus',
            name='rem',
            field=models.CharField(max_length=30),
        ),
    ]
